home/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import login ,logout





app_name = 'home'
urlpatterns = [    
    url(r'^$',views.notes_home , name='notes_home'),
  
]

notes/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('notes/', include('notes_app.urls',namespace='noteeeee')),  # namespace not related to anything :D
    path('accounts/', include('accounts.urls',namespace='accounts')),
    #path('accounts/', include('django.contrib.auth.urls'))  # namespace not related to anything :D
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]

urlpatterns = urlpatterns + static(
                                settings.STATIC_URL,
                                document_root = settings.STATIC_ROOT
                                )
urlpatterns = urlpatterns + static(
                                settings.MEDIA_URL,
                                document_root = settings.MEDIA_ROOT
                                )


admin.site.site_header ="Notes Admin Panel"
admin.site.site_title ="Notes App Admin"
admin.site.site_index_title = "Welcome Notes Admin"

notes_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'noteay7aga'
urlpatterns = [
    url(r'^$',views.all_notes , name='all_notes'),
   # url(r'^(?P<id>\d+)$',views.note_details,name='note_details')
   url(r'^add$',views.add_notes , name='add_notes'),
   url(r'^(?P<slug>[-\w]+)/edit$',views.note_edit,name='edit_note'),
   url(r'^(?P<slug>[-\w]+)/$',views.note_details,name='note_details'),
   

   
]

notes_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.
class Note(models.Model):
    title   = models.CharField(max_length=50)
    content = RichTextField()
    created = models.DateTimeField(auto_now=True, auto_now_add=False)
    slug    = models.SlugField(blank=True, null=True) # Allow no value in Form and DB  :D
    active  = models.BooleanField(default=True)
    tags    = models.CharField(max_length=50)
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    img   = models.ImageField( upload_to='notes-img',null=True,blank=True) #will create automatic on main path  :D

    # This method to assign value to slug field if it doesn't entered by value by overriding save() :D
    def save(self,*args, **kwargs):   
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note,self).save(*args, **kwargs)



    def __str__(self):
        return self.title
    

notes_app/forms.py
from django import forms
from .models import Note
from ckeditor.widgets import CKEditorWidget


class NoteForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Note
        fields = ("title","content","tags","slug","img")

notes_app/views.py
from django.shortcuts import render ,redirect , get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Note
from .forms import NoteForm
from django.contrib import messages
from accounts.models import Profile


# Create your views here.

def all_notes(request):
    if request.user.is_authenticated:            
        user = request.user
        profile = get_object_or_404(Profile,user=user)
        all_notes = Note.objects.filter(user=user)
        context = {
            'all_notes': all_notes,
            'profile':profile
        }
        return render(request,'notes.html',context)
    else:
        return redirect('/accounts/login')

def note_details(request,slug):
    note = Note.objects.get(slug=slug)
    if request.user.is_authenticated:
        user = request.user
        profile = get_object_or_404(Profile,user=user)
        context={
            'note':note,
            'profile':profile
        }
        
        return render(request,'one_note.html',context)
    else:
        context={
            'note':note,
            
        }
        
        return render(request,'one_note.html',context)

def add_notes(request):
    if request.user.is_authenticated:
        user = request.user
        profile = get_object_or_404(Profile,user=user)
        if request.method == 'POST':
            form = NoteForm(request.POST,request.FILES) # constructor

            if form.is_valid():
                new_form = form.save(commit=False)  # class instance or object
                new_form.user = request.user
                new_form.save()
                messages.success(request,'Note has been created successfully.')            
                return redirect('/notes')
        else:
            form = NoteForm()     

    else:
        return redirect('/accounts/login')

    context = {
        'form':form,
        'profile':profile
    }

    return render(request,'add_note.html',context)
    
def note_edit(request,slug):
    if request.user.is_authenticated:
        user = request.user
        profile = get_object_or_404(Profile,user=user)
        note = Note.objects.get(slug=slug)
        if request.method == 'POST':     #means you clicked the button  :D
            form = NoteForm(request.POST,request.FILES,instance=note)
            
            if form.is_valid():
                new_form = form.save(commit=False)  # class instance or object
                new_form.user = request.user
                new_form.save()
                messages.success(request, 'Note has been updated successfully.') 
                return redirect('/notes')
        else:
            form = NoteForm(instance=note)     

        context = {
            'form':form,
            'profile':profile
        }

        return render(request,'edit_note.html',context)
    else:
        return redirect('/accounts/login')

notes_app/templates/add_note.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block body %}
    <div class="row">
        <div class="add_form">
            <form action="" method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {% bootstrap_form form %}<br>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                    Save
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
    
{% endblock body %}

notes_app/templates/all_notes.html
<h1> Welcome in Django with wafa </h1>

<h3>Our notes</h3>
 <a href="{% url 'noteeeee:add_notes' %}">Add note</a>
<br>
<hr> 
{% for note in all_notes  %}
   <a href="{% url 'noteeeee:note_details' note.slug  %}"> {{note}}</a>   
   <br>
{% endfor %}

notes_app/templates/edit_note.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block body %}
    <div class="row">
        <div class="add_form">
            <form action="" method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}                
                {% bootstrap_form form %}
                {{ form.media }}
                {% buttons %}
            <button type="submit" class="btn btn-primary">
            Save
            </button>
        {% endbuttons %}
            </form>
        </div>
    </div>
    
{% endblock body %}

notes_app/templates/note_details.html
<h1>{{note}}</h1> <br>
<hr>
<a href="{% url 'noteeeee:edit_note' note.slug %}">Edit</a>
<br>
<hr> <br>
<h3>{{note.content}}</h3>
<h3>{{note.tags}}</h3>
<h4>{{note.active}}</h4>

<h4>{{note.created}}</h4>

notes_app/templates/notes.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
	<!-- Start blog Area -->
	<section class="blog-area section-gap">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-8 pb-30 header-text">
					<h1>Your Recent Notes</h1>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> labore  et dolore magna aliqua.
					</p>
				</div>
			</div>
			<hr>
			<a href=" {% url 'noteeeee:add_notes' %} "> Add New Note </a><br>
			<hr>
			<div class="row">			
			{% for note in all_notes  %}
				<div class="single-blog col-lg-4 col-md-4">
					{% if note.img %}					
					<img class="f-img img-fluid mx-auto" src="{{note.img.url}}" alt="">
					{% else %}
					<img class="f-img img-fluid mx-auto" src="{% static 'img/no_img.jpg' %}" alt="">
					{% endif %}
					<h4>
						<a href="{% url 'noteeeee:note_details' note.slug  %}">{{note.title}}</a>
					</h4>
					<p>{{note.content|safe|truncatewords:'20'}}<a href="{% url 'noteeeee:note_details' note.slug  %}">read more</a>  <!--for truncate and see more link :D-->
					</p>
					<div class="bottom d-flex justify-content-between align-items-center flex-wrap">
						<div>
							<img class="img-fluid" src="{% static 'img/user.png' %}" alt="">
							<a href="#"><span>{{note.user}}</span></a>
						</div>
						<div class="meta">
							{{note.created|date:"j M"}}
							
						</div>
					</div>
				</div>
			{% endfor %}
			</div>
		</div>
	</section>
	<!-- end blog Area -->

{% endblock body %}

notes_app/templates/one_note.html
{% extends 'base.html' %}	
{% load static %}

{% block body %}
	<!-- Start blog Area -->
	
	<section class="blog-area section-gap">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-8 pb-30 header-text">
					<h1>{{note.title}}</h1> <br>					
					<p>
						{{note.created|date:"j M"}} | {{note.tags}} | {{note.user}}
					</p>
				</div>
			</div><br>
			<hr>
				<a href=" {% url 'noteeeee:add_notes' %} "> Add New Note </a><br> 
				<a href=" {% url 'noteeeee:edit_note' note.slug %} "> Edit </a><br>    
			<hr>
			<div class="row">
			
				<div class="single-blog col-lg-10 col-md-10">
					{% if note.img %}
					<img class="f-img img-fluid mx-auto post_panner "  src="{{note.img.url}}" width="140" height="140" border="0" alt="" >
					{% else %}
					<img class="f-img img-fluid mx-auto post_panner "  src="{% static 'img/no_img.jpg' %}" width="140" height="140" border="0" alt="" >
					{% endif %}
					<h4>
						<a href="#"></a>
					</h4>
					<p>
						{{note.content|safe}}
					</p>
					

					
					<div class="bottom d-flex justify-content-between align-items-center flex-wrap">
						<div>
							<img class="img-fluid" src="img/user.png" alt="">
							<a href="#"><span></span></a>
						</div>
						<div class="meta">
							
							
						</div>
					</div>
				</div>
			
			</div>
		</div>
	</section>
	<!-- end blog Area -->
{% endblock body %}