accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import login ,logout




app_name = 'accounts'
urlpatterns = [    
    url(r'^$',views.home , name='home'),
    #path('',views.home,name='home'),
    url(r'^login/$', views.login,name='login'),    
    #path('login',views.login,name='login'),
    url(r'^logout/$', views.logout ,name='logout'),
    #path('logout',views.logout,name='logout'),
    url(r'^signup/$', views.register ,name='register') ,
    #path('signup',views.register,name='register')
    url(r'^(?P<slug>[-\w]+)/$',views.profile,name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$',views.edit_profile,name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$',views.change_password,name='change_password'),

]

home/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import login ,logout





app_name = 'home'
urlpatterns = [    
    url(r'^$',views.notes_home , name='notes_home'),
  
]

notes/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('notes/', include('notes_app.urls',namespace='noteeeee')),  # namespace not related to anything :D
    path('accounts/', include('accounts.urls',namespace='accounts')),
    #path('accounts/', include('django.contrib.auth.urls'))  # namespace not related to anything :D
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]

urlpatterns = urlpatterns + static(
                                settings.STATIC_URL,
                                document_root = settings.STATIC_ROOT
                                )
urlpatterns = urlpatterns + static(
                                settings.MEDIA_URL,
                                document_root = settings.MEDIA_ROOT
                                )


admin.site.site_header ="Notes Admin Panel"
admin.site.site_title ="Notes App Admin"
admin.site.site_index_title = "Welcome Notes Admin"

accounts/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import datetime
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #first_name= models.CharField(max_length=50)   we remove form profile model because Django provide them automatically
    #last_name= models.CharField( max_length=50)
    headline =models.CharField(max_length=50)
    bio=models.TextField()
    slug = models.SlugField(blank=True, null=True)
    img=models.ImageField(upload_to="profile_img")
    join_date= models.DateField( auto_now=False, auto_now_add=False,default=datetime.datetime.now())


    def save(self,*args, **kwargs):
        if not self.slug :
            self.slug = slugify(self.user)
        super(Profile,self).save(*args, **kwargs)

    def __str__(self):
        #return self.user 
        return '%s' %(self.user)
    
## Signals ## Automatically create profile once user_account created :D

def create_profile(sender , **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile ,sender=User)

accounts/views.py
from django.shortcuts import render ,redirect
from django.contrib import messages
from django.contrib.auth.models import User,auth
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from .models import Profile
from django.shortcuts import get_object_or_404
from .froms import UserForm , ProfileForm
from django.contrib import messages



# Create your views here.
#star Home
def home(request):
    pass
#end Home


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username ,password= password)

        if user is not None:
            auth.login(request,user)
            return redirect('/notes')
        else:
            messages.info(request,'Invalid username or password')
            return redirect('/accounts/login')
    else:
        return render(request,'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def register(request):

    if request.method == 'POST': 
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            if User.objects.filter(username = username).exists():
                messages.info(request,'Username is taken ..')
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                    messages.info(request,'Email is taken')
                    return redirect('register')
            else:
                user = User.objects.create_user(username=username,first_name = first_name ,last_name = last_name ,email = email ,password = password1)
                user.save()
                return redirect('/accounts/login')
        else:
            messages.info(request,'Password is not matched')
            return redirect('register')
        return redirect('/')

    else:
        return render(request,'register.html')

def profile(request,slug):
    profile = get_object_or_404(Profile,slug=slug) #Profile.objects.get(slug=slug)   

    context = {
        'profile':profile
    }
    return render(request,'profile.html',context)

def edit_profile(request , slug):
    profile = get_object_or_404(Profile,slug=slug) #3shan edit 7aga lazm tgeeblo el7aga nfsaha el awl :D 
    if request.method == 'POST':
        user_form = UserForm(request.POST,instance=request.user) 
        profile_form = ProfileForm(request.POST,request.FILES,instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user =user_form.save()

            profile =profile_form.save(commit=False)
            profile.user = user
            if 'img' in request.FILES:
                profile.img = request.FILES['img']
                profile.save()
                messages.success(request, 'Profile has been updated successfully.')
                return redirect('/dit_profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)
    
    
    user = request.user
    profile = get_object_or_404(Profile,user=user)
    context ={
        'user_form':user_form,
        'profile_form':profile_form,
        'profile':profile
    }

    return render(request,'edit_profile.html',context)

def change_password(request,slug):
    if request.user.is_authenticated:
        profile = get_object_or_404 (Profile,slug=slug)
        user = request.user
        profile = get_object_or_404(Profile,user=user)

    

        if request.method == 'POST':
            password_form = PasswordChangeForm(request.user,request.POST)

            if password_form.is_valid():
                password_form.save()
                return redirect('/')


        else:
            password_form = PasswordChangeForm(request.user)
    else:
         return redirect('/accounts/login') 
    
    context={
        'password_form':password_form,
        'profile':profile
    }
    return render(request,'change_password.html',context)

accounts/templates/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}   

{% block body %}
<div class="row">
    <div class="add_form">

    <form action="" method="post" class="form">
        {% csrf_token %}        
        {% bootstrap_form password_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
            Save
            </button>
        {% endbuttons %}
    </form> 
    
</div>
</div>
{% endblock body %}

accounts/templates/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}





   

{% block body %}       

<div class="row">
    <div class="add_form">
    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        {% bootstrap_form profile_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
            Save
            </button>
        {% endbuttons %}
    </form>    
</div>
</div>
 {% endblock body %}

accounts/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block body %}
<div class="row">
    <div class="add_form">
    <h3>Login</h3>
    <form action="" method="post" >
        {% csrf_token %}
    
       <label for="">Username</label><input type="text" name="username""><br>
       <label for="">Password </label><input type="password" name="password"><br>
        {% buttons %}
            <button type="submit" class="btn btn-primary">
            Login
            </button>
        {% endbuttons %}
    </form>
    </div>
    </div>
              
{% endblock body %}
            
            

accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="row">
    <div class="add_form">
        <div class="container">
            <center>
            {% if profile.img %}
                <img src="{{profile.img.url}}" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
            {% else %}
                <img src=" {% static 'img/avatar.png' %} " name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
            {% endif %}
                <h3 class="media-heading">{{profile.user}} <small>USA</small></h3>
                <span><strong>Skills: </strong></span>
                    <span class="label label-warning">HTML5/CSS</span>
                    <span class="label label-info">Adobe CS 5.5</span>
                    <span class="label label-info">Microsoft Office</span>
                    <span class="label label-success">Windows XP, Vista, 7</span>
                </center>
                <hr>
                <center>
                <p class="text-left"><strong>Bio: </strong><br>
                    {{profile.bio}}</p>
                <br>
            </center>
    <a href="{% url 'accounts:edit_profile' profile.slug %}">Edit Profile</a> <br>
    <a href="{% url 'accounts:change_password' profile.slug %}">Change Password</a>
        </div>
    </div>
</div>
    
    {% endblock body %}

accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}



{% block body %}
<div class="row">
    <div class="add_form">
     <h3>Signup</h3>
<form action="" method="post">
    {% csrf_token %}
    <label for="">First name</label><input type="text" name="first_name"><br>
    <label for="">Last name</label><input type="text" name="last_name"><br>
    <label for="">e-mail</label><input type="email" name="email"><br>
    <label for="">Username</label><input type="text" name="username"><br>
    <label for="">Password</label><input type="password" name="password1"><br>
    <label for="">Confirm password</label><input type="password" name="password2"><br>
    <input type="submit" class="btn btn-primary" value="Signup">
</div>
</div>
</form>
    
{% endblock body %}