accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import login ,logout




app_name = 'accounts'
urlpatterns = [    
    url(r'^$',views.home , name='home'),
    #path('',views.home,name='home'),
    url(r'^login/$', views.login,name='login'),    
    #path('login',views.login,name='login'),
    url(r'^logout/$', views.logout ,name='logout'),
    #path('logout',views.logout,name='logout'),
    url(r'^signup/$', views.register ,name='register') ,
    #path('signup',views.register,name='register')
    url(r'^(?P<slug>[-\w]+)/$',views.profile,name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$',views.edit_profile,name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$',views.change_password,name='change_password'),

]

home/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import login ,logout





app_name = 'home'
urlpatterns = [    
    url(r'^$',views.notes_home , name='notes_home'),
  
]

notes/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('notes/', include('notes_app.urls',namespace='noteeeee')),  # namespace not related to anything :D
    path('accounts/', include('accounts.urls',namespace='accounts')),
    #path('accounts/', include('django.contrib.auth.urls'))  # namespace not related to anything :D
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]

urlpatterns = urlpatterns + static(
                                settings.STATIC_URL,
                                document_root = settings.STATIC_ROOT
                                )
urlpatterns = urlpatterns + static(
                                settings.MEDIA_URL,
                                document_root = settings.MEDIA_ROOT
                                )


admin.site.site_header ="Notes Admin Panel"
admin.site.site_title ="Notes App Admin"
admin.site.site_index_title = "Welcome Notes Admin"

notes_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'noteay7aga'
urlpatterns = [
    url(r'^$',views.all_notes , name='all_notes'),
   # url(r'^(?P<id>\d+)$',views.note_details,name='note_details')
   url(r'^add$',views.add_notes , name='add_notes'),
   url(r'^(?P<slug>[-\w]+)/edit$',views.note_edit,name='edit_note'),
   url(r'^(?P<slug>[-\w]+)/$',views.note_details,name='note_details'),
   

   
]

templates/base.html
{% load static %}
	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="Colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Quick notes</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
			<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
            <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
		</head>
		<body>

			<!-- Start Header Area -->
			<header class="default-header">
				<div class="container">
					<div class="header-wrap">
						<div class="header-top d-flex justify-content-between align-items-center">
							<div class="logo">
								<a href="/"><img src="{% static 'img/logo.png' %}" alt=""> Quick notes </a>
							</div>
							<div class="main-menubar d-flex align-items-center">
								<nav class="hide">
									{% if user.is_authenticated %}
										<a href="{% url 'noteeeee:all_notes'%}">Your notes</a>
										<a href="{% url 'accounts:profile' profile.slug %}">Profile</a>
										<a href="{% url 'accounts:logout' %}">Logout</a>
										
									{% else %}
										<a href="{% url 'accounts:login' %}">Login</a>
										<a href="{% url 'accounts:register' %}">Signup</a>
									{% endif %}
									
								</nav>
								<div class="menu-bar"><span class="lnr lnr-menu"></span></div>
							</div>
						</div>
					</div>
				</div>
			</header>
			<!-- End Header Area -->		
			

			{% block body %}
				{% if messages %}
					{% for message in messages %}
					<h2>{{message}}</h2>
					{% endfor %}        
				{% endif %}

            {% endblock body %}
				
			
			


			<!-- start footer Area -->
			<footer class="footer-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-2  col-md-6">
							<div class="single-footer-widget">
								<h6>Top Products</h6>
								<ul class="footer-nav">
									<li><a href="#">Managed Website</a></li>
									<li><a href="#">Manage Reputation</a></li>
									<li><a href="#">Power Tools</a></li>
									<li><a href="#">Marketing Service</a></li>
								</ul>
							</div>
						</div>
						<div class="col-lg-4  col-md-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">Contact Us</h6>
								<p>
									56/8, bir uttam qazi nuruzzaman road, west panthapath, kalabagan, Dhanmondi, Dhaka - 1205
								</p>
								<h3>012-6532-568-9746</h3>
								<h3>012-6532-568-97468</h3>
							</div>
						</div>
						<div class="col-lg-6  col-md-12">
							<div class="single-footer-widget newsletter">
								<h6>Newsletter</h6>
								<p>You can trust us. we only send promo offers, not a single spam.</p>
								<div id="mc_embed_signup">
									<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

										<div class="form-group row" style="width: 100%">
											<div class="col-lg-8 col-md-12">
												<input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
												<div style="position: absolute; left: -5000px;">
													<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
												</div>
											</div>

											<div class="col-lg-4 col-md-12">
												<button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
											</div>
										</div>
										<div class="info"></div>
									</form>
								</div>
							</div>
						</div>
					</div>

					<div class="row footer-bottom d-flex justify-content-between">
						<p class="col-lg-8 col-sm-12 footer-text m-0">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->

			<script src=" {% static 'js/vendor/jquery-2.2.4.min.js' %} "></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
			<script src="{% static 'js/jquery.sticky.js' %}"></script>
			<script src="{% static 'js/parallax.min.js' %}"></script>
			<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
			<script src="{% static 'js/waypoints.min.js' %}"></script>
			<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>
		</body>
	</html>